stages:
  data_splitting:
    cmd: python3 src/data/data_splitting.py
    deps:
    - data/raw/raw.csv
    - params.yaml
    - src/data/data_splitting.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  data_normalization:
    cmd: python3 src/data/data_normalization.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/data_normalization.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  grid_search:
    cmd: python3 src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - params.yaml
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/model.pkl
  evaluation:
    cmd: python3 src/models/evaluate_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
